<a href="https://colab.research.google.com/github/Avinash505/AIandMachinlearning/blob/main/Women_Clothes_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Women Clothes Review

# impor libraries 

In [ ]:
import pandas as pd


In [ ]:
import numpy as np


In [ ]:
import matplotlib.pyplot as plt


In [ ]:
import seaborn as sns


# import Data 

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/DhruvBhirud/datasets/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')


In [ ]:
df.head()


Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


# Missing Value


In [ ]:
df.isna().sum()


Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df[df['Review Text']==""]=np.NaN


In [ ]:
df['Review Text'].fillna("No Review",inplace=True)


In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
"df['Review Text']"

"df['Review Text']"

# Define y and X

In [ ]:
df.columns


Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [ ]:
X = df['Review Text']


In [ ]:
y = df['Rating']


In [ ]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# Train Test Split


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, stratify=y,random_state=12529)


# Get Feature Text Conversion to Tokens


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


In [ ]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3),stop_words='english',max_features=5000)


In [ ]:
X_train = cv.fit_transform(X_train)


In [ ]:
cv.get_feature_names_out()


array(['0p fit', '10 10', '10 12', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [ ]:
X_train.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test = cv.fit_transform(X_test)

In [ ]:
cv.get_feature_names_out()

array(['10 12', '10 fit', '10 got', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Get Model Train


In [ ]:
from sklearn.naive_bayes import MultinomialNB


In [ ]:
model = MultinomialNB()


In [ ]:
model.fit(X_train, y_train)


MultinomialNB()

# Get Model Prediction

In [ ]:
y_pred = model.predict(X_test)


In [ ]:
y_pred


array([5., 1., 5., ..., 3., 4., 4.])

# Get Probability of Each Predict Class

In [ ]:
model.predict_proba(X_test)


array([[0.05195875, 0.08260154, 0.17570434, 0.22106802, 0.46866734],
       [0.36050981, 0.05009674, 0.11403525, 0.15638324, 0.31897497],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.05656578, 0.02108659, 0.48254844, 0.02343763, 0.41636156],
       [0.01070241, 0.00656414, 0.00939201, 0.92843325, 0.04490819],
       [0.03736085, 0.04541674, 0.05181356, 0.4371705 , 0.42823834]])

# Get Model Evaluation


In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

[[  18   28   29   48  130]
 [  60   40   46  102  222]
 [ 101   86  100  185  389]
 [ 191  161  166  321  684]
 [ 421  401  355  788 1974]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.03       253
         2.0       0.06      0.09      0.07       470
         3.0       0.14      0.12      0.13       861
         4.0       0.22      0.21      0.22      1523
         5.0       0.58      0.50      0.54      3939

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046



# Recategories Rating as Poor 0 and Good 1

In [ ]:
df['Rating'].value_counts()


5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [ ]:
df.replace({'Rating': {1:0,2:0,3:0,4:1,5:1}}, inplace=True)


In [ ]:
y=df['Rating']


In [ ]:
X=df['Review Text']


# Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.7,random_state=12529)

# Get Feature Text Conversion to Tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)
X_train = cv.fit_transform(X_train)
X_test = cv.fit_transform(X_test)

# Get Model ReTrain

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

# Get Model Prediction


In [ ]:
y_pred = model.predict(X_test)
y_pred

array([1., 0., 1., ..., 1., 1., 1.])

#Get Model Evaluation

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))


[[ 416 1145]
 [ 979 4506]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.30      0.27      0.28      1561
         1.0       0.80      0.82      0.81      5485

    accuracy                           0.70      7046
   macro avg       0.55      0.54      0.55      7046
weighted avg       0.69      0.70      0.69      7046



# That's it 